# docker-compose.yml
version: "3.9"
services:
  webapp:
    build:
      context: .
      dockerfile: docker/Dockerfile.development
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_volume:/var/lib/mysql
      - ./docker/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "9906:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
volumes:
  db_volume: